name: test ci
on:
  workflow_dispatch:

jobs:
  prepare-release:
    name: Test CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update README
        run: echo test123 > README.md

      - name: Commit version prepare
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'Commit Test'
          file_pattern: '*'
