name: cross platform test
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  GSTREAMER_WIN_PATH: D:\gstreamer\

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        isPR:
          - ${{ github.event_name == 'pull_request' }}
        labeledUbuntu:
          - ${{ github.event.pull_request && contains(github.event.pull_request.labels.*.name, format('CI{0} Ubuntu', ':')) }}
        labeledMacOS:
          - ${{ github.event.pull_request && contains(github.event.pull_request.labels.*.name, format('CI{0} macOS', ':')) }}
        labeledWindows:
          - ${{ github.event.pull_request && contains(github.event.pull_request.labels.*.name, format('CI{0} Windows', ':')) }}
        # excludes ubuntu, unless the label 'Ubuntu (CI)' is added
        exclude:
          - labeledUbuntu: false
            isPR: true
            os: 'ubuntu-latest'
          - labeledMacOS: false
            isPR: true
            os: 'macos-latest'
          - labeledWindows: false
            isPR: true
            os: 'windows-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install developer package dependencies (Linux)
        if: runner.os == 'Linux'
        run: >
          sudo apt-get update && sudo apt-get install -y
          libpulse-dev portaudio19-dev libasound2-dev libsdl2-dev
          gstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          libavahi-compat-libdnssd-dev

      - name: Install pkg-config
        if: runner.os == 'Windows'
        run: choco install pkgconfiglite bonjour

      - name: Cache gstreamer
        uses: actions/cache@v4
        if: runner.os == 'Windows'
        id: cache-gstreamer
        with:
          path: ${{ env.GSTREAMER_WIN_PATH }}
          key: gstreamer-windows-${{ hashFiles('**/Cargo.lock') }}

      - name: Install gstreamer (Windows)
        if: ${{ !steps.cache-gstreamer.outputs.cache-hit && runner.os == 'Windows' }}
        run: choco install gstreamer-devel

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install gstreamer portaudio

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        env:
          PKG_CONFIG_PATH: ${{ env.GSTREAMER_WIN_PATH }}1.0\msvc_x86_64\lib\pkgconfig
        run: cargo build --frozen
