name: win-build.yml
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  GSTREAMER_WIN_PATH: D:\gstreamer\
  GSTREAMER_WIN_CACHE_KEY: gstreamer-windows-${{ hashFiles('**/Cargo.lock') }}

jobs:
  lookup-cache:
    name: lookup cache
    runs-on: windows-latest
    outputs:
      gstreamer-cache: ${{ steps.gstreamer-lookup.outputs.cache-hit }}
    steps:
      - name: loop gstreamer cache
        id: gstreamer-lookup
        uses: actions/cache@v4
        with:
          lookup-only: 'true'
          path: ${{ env.GSTREAMER_WIN_PATH }}
          key: ${{ env.GSTREAMER_WIN_CACHE_KEY }}

  build:
    needs: lookup-cache
    name: windows build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install pkg-config
        run: choco install pkgconfiglite

      - name: Cache gstreamer
        uses: actions/cache@v4
        with:
          path: ${{ env.GSTREAMER_WIN_PATH }}
          key: ${{ env.GSTREAMER_WIN_CACHE_KEY }}

      - run: echo "${{ needs.lookup-cache.outputs.gstreamer-cache }}"

      - name: Install gstreamer
        if: ${{ needs.lookup-cache.outputs.gstreamer-cache != true }}
        run: choco install gstreamer-devel

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        env:
          PKG_CONFIG_PATH: ${{ env.GSTREAMER_WIN_PATH }}1.0\msvc_x86_64\lib\pkgconfig
        run: cargo build --frozen
