name: win-build.yml
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  GSTREAMER_WIN_PATH: D:\gstreamer\

jobs:
  build:
    name: windows build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install pkg-config
        run: choco install pkgconfiglite bonjour

      - name: Cache gstreamer
        uses: actions/cache@v4
        id: cache-gstreamer
        with:
          path: ${{ env.GSTREAMER_WIN_PATH }}
          key: gstreamer-windows-${{ hashFiles('**/Cargo.lock') }}

      - name: test
        run: echo "${{ steps.cache-gstreamer.outputs.cache-hit }}"

      - name: Install gstreamer
        if: ${{ !steps.cache-gstreamer.outputs.cache-hit }}
        run: choco install gstreamer-devel

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        env:
          PKG_CONFIG_PATH: ${{ env.GSTREAMER_WIN_PATH }}1.0\msvc_x86_64\lib\pkgconfig
        run: cargo build --frozen
