name: win-build.yml
on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

jobs:
  build:
    name: windows build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache gstreamer
        uses: actions/cache@v4
        with:
          path: D:\gstreamer
          key: gstreamer-${{ runner }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install pkg-config
        run: choco install pkgconfiglite

      - name: Install gstreamer
        if: ${{ hashFiles('assets/') == '' }}
        run: choco install gstreamer-devel

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        env:
          PKG_CONFIG_PATH: D:\gstreamer\1.0\msvc_x86_64\lib\pkgconfig
        run: cargo build --frozen
